### ISSUE TITLE
Listing printer drivers times out and gives 'Success' if ends with error

### ISSUE THREAD

**Issue by hhl** [OpenPrinting/cups#641]
```
`apt policy cups cups-filters
cups:
  Installed: 2.4.2-2

cups-filters:
  Installed: 1.28.17-2`
```

I am unable to connect/install my network printer (HP LaserJet 4250i dtn).

```
Add Printer HP_LaserJet_4250 Error
Unable to get list of printer drivers:
Success
```
```
lpinfo -v

network beh
file cups-brf:/
network socket
network ipps
network lpd```
LANG=C lpinfo -v
network beh
file cups-brf:/
network socket
network ipps
network lpd
network https
network http
network ipp
network smb
network bjnp
network socket://192.168.0.105
```
```
lpinfo -m

lpinfo: Success
```
I really think that is not a success!

So, what shall/can I do to solve that problem?
